name: neon_fire
description: "프로해빗 - 운동 기록 관리 앱"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  #UI 라이브러리
  cupertino_icons: ^1.0.8

  # Firebase 라이브러리
  firebase_core: ^4.2.1 #초기화용
  firebase_auth: ^6.1.2 #인증용
  cloud_firestore: ^6.1.0  #데이터베이스용
  firebase_storage: ^13.0.4  #이미지 저장용

  # URL 런처 #YouTube 링크 열기
  url_launcher: ^6.2.2  

  # 이미지 피커
  image_picker: ^1.0.7
  
  # 파일 핸들링
  path_provider: ^2.1.1

  # 차트 라이브러리
  fl_chart: ^0.65.0  

  # 상태 관리
  provider: ^6.1.1

  # 라우팅
  go_router: ^14.6.2

  # 국제화 및 포맷팅
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/muscle/
    - assets/images/product/
    - assets/icons/icon.png

